-- CURRENT VERSION APLICATION 0.2 --
CREATE TABLE IF NOT EXISTS `Status` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Descricao VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Item` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Nome VARCHAR(16) NOT NULL,
    Status INTEGER NOT NULL,
    FOREIGN KEY (Status) REFERENCES `Status` (ID)
);

INSERT INTO Status VALUES (NULL, 'À comprar'), (NULL, 'Orçamento feito'), (NULL, 'Comprado');